exception Exn;

let raise = () => raise(Exn);